source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'BezierShrinkwrap_Example', :exclusive => true do
  pod "BezierShrinkwrap", :path => "../"
end

target 'BezierShrinkwrap_Tests', :exclusive => true do
  pod "BezierShrinkwrap", :path => "../"

  
end
